[project]
name = "jaga"
version = "0.1.0"
description = "A Flask application to retrieve and manage tasks"
dependencies = [
    "flask==3.1.2",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
