services:
  jaga:
    container_name: jaga
    build:
      context: ..
      target: run
      args: {}
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      - SERVER_NAME=localhost:8888
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres/jaga
      - AUTH_NAME=azure
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - AUTH_ACCESS_TOKEN_URL=https://login.microsoftonline.com/804d6f85-9188-4618-ae1d-e387fe7fc33c/oauth2/v2.0/token
      - AUTH_AUTHORIZE_URL=https://login.microsoftonline.com/804d6f85-9188-4618-ae1d-e387fe7fc33c/oauth2/v2.0/authorize
      - AUTH_SCOPE=openid profile email
      - AUTH_JWKS_URI=https://login.microsoftonline.com/804d6f85-9188-4618-ae1d-e387fe7fc33c/discovery/v2.0/keys
 
  postgres:
    container_name: postgres
    image: postgres:15.15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jaga
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: