services:
  jaga:
    container_name: jaga
    build:
      context: ..
      target: run
      args: {}
    ports:
      - "8888:8888"
    # depends_on:
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres/jaga
  
  postgres:
    container_name: postgres
    image: postgres:15.15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jaga
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: